### ISSUE TITLE
Old version of KSCrash?

### ISSUE THREAD

**Issue by keithslater** [getsentry/sentry-objc#2]
KSCrash is causing these compile errors - 

`Pods/KSCrash/Source/KSCrash/Recording/Tools/KSMachApple.h:173:2: ARC forbids Objective-C objects in struct`
`Pods/KSCrash/Source/KSCrash/Recording/Tools/KSObjCApple.h:425:8: ARC forbids Objective-C objects in union`

Looks like version 0.0.4 is being used which is 3 years old. Any reason this old version is used?

**Comment by HazAT** [comment]
We use a recent version of KSCrash now
