### ISSUE TITLE
Support for overriding release

### ISSUE THREAD

**Issue by nevir** [getsentry/sentry-objc#3]
It'd be helpful to be able to override the `release` attribute on events!

(For example, we tend to prefer using a git sha for the release)

**Comment by dcramer** [comment]
@nevir fwiw you should use sentry-swift if you can (its our full featured cocoa repo) -- this repo is intended for compatibility with older platforms like Unity, and likely won't support the full feature set

**Comment by nevir** [comment]
Ah, doh; thanks for the pointer!

You might want to add that as a big disclaimer at the top of this repo (and raven-objc, raven-swift) - it's a bit confusing to track down :P
